#undef ENABLE_NLS
#undef HAVE_CATGETS
#undef HAVE_GETTEXT
#undef HAVE_LC_MESSAGES
#undef HAVE_STPCPY
#undef HAVE_LIBSM
#undef PACKAGE
#undef VERSION
#undef GETTEXT_PACKAGE
#undef GNOME_EXPLICIT_TRANSLATION_DOMAIN
#undef clock_t
#undef fpos_t
#undef L_tmpnam
#undef HAVE_STAT_ST_INO
#undef remove
#undef SEEK_SET
#undef INT_MAX
#undef CUSTOM_CONFIGURATION_FILE
#undef MACROS_USE_PATTERNS
#define DEFAULT_FILE_FORMAT	2
#undef SYS_INTERPRETER
#ifndef INTERNAL_SORT
# undef EXTERNAL_SORT
#endif
#undef TMPDIR
#undef REGCOMP_BROKEN
#undef CHECK_REGCOMP
#undef __USE_FIXED_PROTOTYPES__
#undef NON_CONST_PUTENV_PROTOTYPE
#undef NEED_PROTO_REMOVE
#undef NEED_PROTO_UNLINK
#undef NEED_PROTO_MALLOC
#undef NEED_PROTO_GETENV
#undef NEED_PROTO_FGETPOS
#undef NEED_PROTO_STAT
#undef NEED_PROTO_LSTAT
#undef NEED_PROTO_TRUNCATE
#undef NEED_PROTO_FTRUNCATE
